my_tpl = ('a', 'b', 'c', 'd', 'e')
print(my_tpl[1:])
print(my_tpl[:4])
print(my_tpl[1:4])
print(my_tpl[-4:-1])
print(my_tpl[1:-1])
print(my_tpl[-4:4])
print(my_tpl[::2])
print(my_tpl[::-2])
print(my_tpl[1:4:2])
print(my_tpl[4:1:-2])
print(my_tpl[-4:-1:2])
print(my_tpl[-1:-4:-2])