my_lst = ['a', 'b', ['cc', 'dd', ['eee', 'fff']], 'g', 'h']
print(my_lst[-1])
print(my_lst[-2])
print(my_lst[-3])
print(my_lst[-4])
print(my_lst[-5])
print(my_lst[-3][-1])
print(my_lst[-3][-2])
print(my_lst[-3][-3])
print(my_lst[-3][-1][-1])
print(my_lst[-3][-1][-2])